# Generated by Django 4.2.7 on 2023-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='media/')),
                ('date_create', models.IntegerField()),
                ('published', models.BooleanField(default=True)),
                ('views_count', models.IntegerField()),
            ],
        ),
    ]
