# Generated by Django 4.2.7 on 2023-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
